# Excercice de conteneurisation pour Django. Utiliser l'app (Polls) du tuto Django.
# Name au top-level définit le nom du projet
name: djangoTutorial

services:
  app:
    image: rustled/django-debian
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - ./:/app
  bd:
    image: postgres:18
    environnement:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
